version: '3.8'

services:
  neo4j:
    image: neo4j:5.25.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - neo4j-network
    volumes:
      - neo4j-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - neo4j-network
    volumes:
      - backend-data:/backend

networks:
  neo4j-network:
    driver: bridge

volumes:
  neo4j-data:
  backend-data: