version: '3.8'

services:
  db:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - neo4j-network
    volumes:
      - neo4j-data:/data
      - neo4j-import:/var/lib/neo4j/import

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_ENV=development
      - NEO4J_URI=bolt://db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - db
    networks:
      - neo4j-network
    volumes:
      - neo4j-import:/backend/app/models/dumps

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:4200"
    networks:
      - neo4j-network

networks:
  neo4j-network: 
    driver: bridge

volumes:
  neo4j-data:
  neo4j-import:
